In [1]:
#numpy

In [2]:
import numpy as np
import pandas as pd

In [3]:
df1= pd.DataFrame(columns=["X1"])
np.random.normal(5,1,size=(1,3))

array([[4.09146198, 4.71559166, 4.70941116]])

In [4]:
df1['X1']=np.random.normal(5,2,size=10)

In [5]:
df1

X1
0   8.644530
1   3.273045
2   2.359778
3  10.043571
4   4.301955
5   6.021977
6   6.598445
7   8.159107
8   7.950521
9   7.107239

In [6]:
np.random.randint(4,10, size=6)

array([7, 6, 6, 4, 7, 5])

In [7]:
np.arange(0,10,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [8]:
df2 = np.random.randint(1,100,size=(5,4))

In [9]:
df2

array([[32, 15, 56, 72],
       [84, 89, 11, 94],
       [63, 85, 74,  5],
       [43, 16,  6, 15],
       [37, 18, 61, 12]])

In [10]:
df2[2,1]

85

In [11]:
df2[4,-2]

61

In [12]:
df2[1]

array([84, 89, 11, 94])

In [13]:
df2[:,1]

array([15, 89, 85, 16, 18])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x2 = np.arange(10)
x2=np.random.normal(10,1,size=(2,5))

In [28]:
x2

array([[11.06052485,  8.44662232,  7.88236314,  9.80958419,  9.11461315],
       [10.80315861, 11.50875021,  9.03099699, 10.3971664 ,  9.66906304]])

In [31]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
X1=np.random.random(5)
np.vstack([x2,X1])

array([[1.10605248e+01, 8.44662232e+00, 7.88236314e+00, 9.80958419e+00,
        9.11461315e+00],
       [1.08031586e+01, 1.15087502e+01, 9.03099699e+00, 1.03971664e+01,
        9.66906304e+00],
       [6.74700836e-01, 4.65913903e-01, 8.54143112e-03, 5.57017232e-01,
        9.43216362e-01]])

In [38]:
X3=np.random.random(2).reshape(2,1)

In [39]:
X3

array([[0.70461422],
       [0.37265497]])

In [40]:
np.hstack([x2,X3])

array([[11.06052485,  8.44662232,  7.88236314,  9.80958419,  9.11461315,
         0.70461422],
       [10.80315861, 11.50875021,  9.03099699, 10.3971664 ,  9.66906304,
         0.37265497]])

In [41]:
x4= np.random.random(50).reshape(5,10)

In [42]:
x4

array([[0.22252839, 0.5650835 , 0.40132387, 0.03024091, 0.15340693,
        0.71891938, 0.81844718, 0.01805298, 0.33098046, 0.54553815],
       [0.27184227, 0.98250956, 0.22954095, 0.58016094, 0.80134229,
        0.16762064, 0.39784912, 0.16150739, 0.8365283 , 0.32229932],
       [0.57878529, 0.25153508, 0.34249803, 0.74292872, 0.15713402,
        0.79819682, 0.88670407, 0.74679063, 0.70870791, 0.79748802],
       [0.42846337, 0.21646138, 0.86003281, 0.80666094, 0.72916534,
        0.00395464, 0.98970068, 0.83832873, 0.269689  , 0.67534354],
       [0.67768891, 0.76128476, 0.79717681, 0.41019822, 0.23736457,
        0.74660327, 0.37748829, 0.98458209, 0.74108351, 0.55830694]])

In [46]:
train,test=np.vsplit(x4,[2])

In [47]:
train

array([[0.22252839, 0.5650835 , 0.40132387, 0.03024091, 0.15340693,
        0.71891938, 0.81844718, 0.01805298, 0.33098046, 0.54553815],
       [0.27184227, 0.98250956, 0.22954095, 0.58016094, 0.80134229,
        0.16762064, 0.39784912, 0.16150739, 0.8365283 , 0.32229932]])

In [49]:
def computer21(values):
    output=np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
    return output

In [53]:
values = np.random.random(2)
computer21(values)

array([1.64891048, 1.39361856])

In [54]:
values

array([0.60646106, 0.71755646])

In [55]:
len(values)

2

In [85]:
def whatup(x):
    c =np.empty(len(x))
    for i in range(len(x)):
        c[i]= 0 + x[i]/x[i]
    return np.sum(c)

In [86]:
x=np.random.random(10)
whatup(x)

10.0

In [88]:
x2

array([[11.06052485,  8.44662232,  7.88236314,  9.80958419,  9.11461315],
       [10.80315861, 11.50875021,  9.03099699, 10.3971664 ,  9.66906304]])

In [89]:
np.exp(x2)

array([[63609.92846745,  4659.30845825,  2650.12779747, 18207.41465702,
         9087.11861871],
       [49175.8836827 , 99583.34512298,  8358.1884524 , 32766.64637537,
        15820.51884619]])

In [90]:
np.log(x2)

array([[2.40338245, 2.13376664, 2.06462775, 2.28335989, 2.20987897],
       [2.37983856, 2.44310763, 2.20066277, 2.34153331, 2.26893141]])

In [93]:
np.log10(x2)

array([[1.04377574, 0.92668308, 0.89665644, 0.9916506 , 0.95973824],
       [1.03355075, 1.06102816, 0.9557357 , 1.01691499, 0.98538439]])

In [96]:
x=np.arange(3)
x

array([0, 1, 2])

In [99]:
np.add.reduce(x)

3

In [100]:
np.add.accumulate(x)

array([0, 1, 3], dtype=int32)

In [101]:
x2

array([[11.06052485,  8.44662232,  7.88236314,  9.80958419,  9.11461315],
       [10.80315861, 11.50875021,  9.03099699, 10.3971664 ,  9.66906304]])

In [105]:
np.percentile(x2,95)

11.30704879687774